export const restaurantList = [
  {
    id: 1,
    name: "톰스키친",
    menu: "파스타",
    distance: 5,
    review: 3,
    image: require("../assets/images/restaurantImage/image01.png"),
  },
  {
    id: 2,
    name: "구스토리아",
    menu: "파스타",
    distance: 3,
    review: 2,
    image: require("../assets/images/restaurantImage/image02.png"),
  },
  {
    id: 3,
    name: "프렌밀리 Cafe&Bar",
    menu: "파스타",
    distance: 7,
    review: 4,
    image: require("../assets/images/restaurantImage/image03.png"),
  },
  {
    id: 4,
    name: "더큐어링",
    menu: "파스타",
    distance: 10,
    review: 5,
    image: require("../assets/images/restaurantImage/image04.png"),
  },
  {
    id: 5,
    name: "뚜스뚜스 흑석역점",
    menu: "파스타",
    distance: 6,
    review: 3,
    image: require("../assets/images/restaurantImage/image05.png"),
  },
  {
    id: 6,
    name: "우뇽파스타뚝배기스파게티",
    menu: "파스타",
    distance: 4,
    review: 2,
    image: require("../assets/images/restaurantImage/image06.png"),
  },
  {
    id: 7,
    name: "토마트",
    menu: "파스타",
    distance: 5,
    review: 4,
    image: require("../assets/images/restaurantImage/image07.png"),
  },
  {
    id: 8,
    name: "공미학 루프앤테라스 상도점",
    menu: "파스타",
    distance: 9,
    review: 3,
    image: require("../assets/images/restaurantImage/image08.png"),
  },
  {
    id: 9,
    name: "탭하우스더슈라인",
    menu: "파스타",
    distance: 12,
    review: 5,
    image: require("../assets/images/restaurantImage/image09.png"),
  },
  {
    id: 10,
    name: "라이베쿠헨",
    menu: "파스타",
    distance: 7,
    review: 3,
    image: require("../assets/images/restaurantImage/image10.png"),
  },
  {
    id: 11,
    name: "양궈푸마라탕 중앙대점",
    menu: "마라탕",
    distance: 8,
    review: 5,
    image: require("../assets/images/restaurantImage/image11.png"),
  },
  {
    id: 12,
    name: "황비홍마라탕 상도점",
    menu: "마라탕",
    distance: 14,
    review: 2,
    image: require("../assets/images/restaurantImage/image12.png"),
  },
  {
    id: 13,
    name: "칠기마라샹궈마라탕 중앙대점",
    menu: "마라탕",
    distance: 4,
    review: 6,
    image: require("../assets/images/restaurantImage/image13.png"),
  },
  {
    id: 14,
    name: "미가양꼬치",
    menu: "마라탕",
    distance: 9,
    review: 3,
    image: require("../assets/images/restaurantImage/image14.png"),
  },
  {
    id: 15,
    name: "샹츠마라 숭실대점",
    menu: "마라탕",
    distance: 12,
    review: 4,
    image: require("../assets/images/restaurantImage/image15.png"),
  },
  {
    id: 16,
    name: "신룽푸마라탕 중앙대점",
    menu: "마라탕",
    distance: 6,
    review: 7,
    image: require("../assets/images/restaurantImage/image16.png"),
  },
  {
    id: 17,
    name: "진푸중화요리",
    menu: "마라탕",
    distance: 11,
    review: 1,
    image: require("../assets/images/restaurantImage/image17.png"),
  },
  {
    id: 18,
    name: "라사천마라탕 상도점",
    menu: "마라탕",
    distance: 7,
    review: 5,
    image: require("../assets/images/restaurantImage/image18.png"),
  },
  {
    id: 19,
    name: "마라탕 마라농장",
    menu: "마라탕",
    distance: 3,
    review: 2,
    image: require("../assets/images/restaurantImage/image19.png"),
  },
  {
    id: 20,
    name: "라화쿵부 상도역점",
    menu: "마라탕",
    distance: 5,
    review: 6,
    image: require("../assets/images/restaurantImage/image20.png"),
  },
];
