export const shareList = [
  {
    restaurant: "톰스키친",
    menu: "샐러드파스타",
    name: "foodie_jane",
    image: require("../assets/images/restaurantImage/image01.png"),
    review: [30, 20, 10, 59],
  },
  {
    restaurant: "구스토리아",
    menu: "알리오올리오",
    name: "eats_with_emma",
    image: require("../assets/images/restaurantImage/image02.png"),
    review: [45, 67, 88, 22],
  },
  {
    restaurant: "프렌밀리 Cafe&Bar",
    menu: "트러플파스타",
    name: "dine_out_dan",
    image: require("../assets/images/restaurantImage/image03.png"),
    review: [90, 56, 75, 43],
  },
  {
    restaurant: "더큐어링",
    menu: "토마토파스타",
    name: "tasty_tom",
    image: require("../assets/images/restaurantImage/image04.png"),
    review: [15, 24, 66, 89],
  },
  {
    restaurant: "뚜스뚜스 흑석역점",
    menu: "크림파스타",
    name: "savor_sarah",
    image: require("../assets/images/restaurantImage/image05.png"),
    review: [50, 44, 33, 76],
  },
  {
    restaurant: "우뇽파스타뚝배기스파게티",
    menu: "로제파스타",
    name: "yum_yuri",
    image: require("../assets/images/restaurantImage/image06.png"),
    review: [77, 88, 99, 11],
  },
  {
    restaurant: "토마트",
    menu: "치킨파스타",
    name: "nom_nom_nick",
    image: require("../assets/images/restaurantImage/image07.png"),
    review: [23, 34, 56, 78],
  },
  {
    restaurant: "공미학 루프앤테라스 상도점",
    menu: "봉골레파스타",
    name: "bites_with_ben",
    image: require("../assets/images/restaurantImage/image08.png"),
    review: [34, 45, 67, 89],
  },
  {
    restaurant: "탭하우스더슈라인",
    menu: "해물파스타",
    name: "gourmet_gina",
    image: require("../assets/images/restaurantImage/image09.png"),
    review: [67, 34, 23, 90],
  },
  {
    restaurant: "라이베쿠헨",
    menu: "까르보나라",
    name: "feast_with_felix",
    image: require("../assets/images/restaurantImage/image10.png"),
    review: [77, 55, 33, 80],
  },
  {
    restaurant: "양궈푸마라탕 중앙대점",
    menu: "왕가마라탕",
    name: "munchy_maya",
    image: require("../assets/images/restaurantImage/image11.png"),
    review: [45, 23, 88, 67],
  },
  {
    restaurant: "황비홍마라탕 상도점",
    menu: "미쳐버린마라탕",
    name: "devour_dylan",
    image: require("../assets/images/restaurantImage/image12.png"),
    review: [22, 33, 44, 55],
  },
  {
    restaurant: "칠기마라샹궈마라탕 중앙대점",
    menu: "얼큰마라탕",
    name: "plate_paul",
    image: require("../assets/images/restaurantImage/image13.png"),
    review: [50, 60, 70, 80],
  },
  {
    restaurant: "미가양꼬치",
    menu: "단짠마라탕",
    name: "crave_chloe",
    image: require("../assets/images/restaurantImage/image14.png"),
    review: [10, 20, 30, 40],
  },
  {
    restaurant: "샹츠마라 숭실대점",
    menu: "해물마라탕",
    name: "taste_ted",
    image: require("../assets/images/restaurantImage/image15.png"),
    review: [15, 25, 35, 45],
  },
  {
    restaurant: "신룽푸마라탕 중앙대점",
    menu: "순한마라탕",
    name: "savory_sophie",
    image: require("../assets/images/restaurantImage/image16.png"),
    review: [90, 80, 70, 60],
  },
  {
    restaurant: "진푸중화요리",
    menu: "짬뽕마라탕",
    name: "bite_bella",
    image: require("../assets/images/restaurantImage/image17.png"),
    review: [65, 75, 85, 95],
  },
  {
    restaurant: "라사천마라탕 상도점",
    menu: "정통마라탕",
    name: "munching_mike",
    image: require("../assets/images/restaurantImage/image18.png"),
    review: [30, 40, 50, 60],
  },
  {
    restaurant: "마라탕 마라농장",
    menu: "푸주마라탕",
    name: "delightful_daisy",
    image: require("../assets/images/restaurantImage/image19.png"),
    review: [35, 45, 55, 65],
  },
  {
    restaurant: "라화쿵부 상도역점",
    menu: "국물없는마라탕",
    name: "taste_test_tommy",
    image: require("../assets/images/restaurantImage/image20.png"),
    review: [80, 70, 60, 50],
  },
];
